### ISSUE TITLE
MDC successor

### ISSUE THREAD

**Issue by ghost** [tekartik/mdl_js.dart#1]
Do you know if anyone has done MDC.
MDL is end of life

**Comment by alextekartik** [comment]
I started months ago without going very far https://github.com/tekartik/mdc_js.dart but i guess it is already out-of-date. I won't look at it until i have a need (typically small webapp without angular) and I'm not aware of any work on that, sorry!

**Comment by ghost** [comment]
Thanks for reply.

Well I have a need and so I think I can thrown together a kitchen sink
using it.

Will put on GitHub

Cheers

Gerard
